### ISSUE TITLE
"Invalid" Status after Update-ACMEIdentifier -Ref example.com_Alias

### ISSUE THREAD

**Issue by hmatt843** [ebekker/ACMESharp#115]
Paging bseddon or anyone else who may be able to help...!

I've been following this video's instructions ( https://www.youtube.com/watch?v=SVUY7ygbGm8 ) for installing a Let'sEncrypt certificate using ACMESharp.

My exact steps: Open both powershell versions as Administrator

Set-ExecutionPolicy Unrestricted for both

Then type in PowerShell (x86):

mkdir c:\Vault

cd c:\Vault

Import-Module ACMEPowerShell

Initialize-ACMEVault -BaseURI https://acme-v01.api.letsencrypt.org/

New-ACMERegistration -Contacts mailto:myemail@gmail.com

Update-ACMERegistration -AcceptTOS

New-ACMEIdentifier -Dns example.com -Alias example.com_Alias 

New-ACMEProviderConfig -WebServerProvider IisSitePath -Alias example.com_Provider

( Change the path to C:\\inetpub\\wwwroot )

Get-ACMEIdentifier -Ref example.com_Alias

Complete-ACMEChallenge -Ref example.com_Alias -Challenge http-01 -ProviderConfig example.com_Provider

( Go to https://www.example.com/.well-known/acme-challenge/ID to make sure it works, and it does for me )

( To prevent the web.config bug, I copy the web.config and paste it into the parent folder, then edit the pasted version so that the * is removed. )

Then back in PowerShell (x86):

Submit-ACMEChallenge -Ref example.com_Alias -Challenge http-01

Update-ACMEIdentifier -Ref example.com_Alias

And this is where I get the invalid: http://imgur.com/cYQ89LF.jpg

The strangest part is that I actually got a certificate working BEFORE using these steps. I don't think I did anything different then to what I'm doing now. 

What might be the cause of my error?

Thank you.

Edit: I tried repeating these steps with a changed alias (-Ref example.com_Alias-2016-03-19 ) and the problem persists.

Also, I did confirm by going to the URL on my site ( http://www.example.com/.well-known/acme-challenge/eR4fvLaoMVLUPwkFIqqsX5-CeLXEg6sYAftV-Mx99LI ) that it is returning "eR4fvLaoMVLUPwkFIqqsX5-CeLXEg6sYAftV-Mx99LI.hK5MvxBP5pcSlRvaLtg7etSFNlnFlFSfHMo-GHuBV4w" in plain text, which I would assume is desired since this is the same behavior from when this process was successful before.

**Comment by bseddon** [comment]
How have you created the file?  It is really important that the file 'eR4fvLaoMVLUPwkFIqqsX5-CeLXEg6sYAftV-Mx99LI' is not saved using unicode and that there is no carriage return at the end of the token in the file. If either of these are true then the LE servers will report invalid data.  You don't include above an of the transcript and you have not provided the challenge url (on the LE servers) so its not possible to help rule out this as a potential explanation.

I've just created a challenge (New-ACMEIdentifer ...thru... Submit-ACMEChallenge) but created a token file with an extra carriage return.  The challenge is invalid.  You can see the error on the LE server page for the identifier created.

https://acme-v01.api.letsencrypt.org/acme/authz/VFMzhM3967zS8KoBQxLSZaIG15BbyDI7QbOYJfx9TN8

As you can see, the message is:

```
"Error parsing key authorization file: Invalid key authorization: malformed key thumbprint"
```
Do you see an error message like this in the equivalent page for your identifier?

**Comment by hmatt843** [comment]
First of all, thank you for your being so helpful and reliable here.

I didn't know I could check the URL like that. That is neat and useful! I do see the error:

"detail":"Invalid response from http://example.com/.well-known/acme-challenge/eR4fvLaoMVLUPwkFIqqsX5-CeLXEg6sYAftV-Mx99LI [199.44.81.30]: 404

So that indeed possibly points to the cause being the Unicode problem? Honestly, I am unsure how to control how the token file is saved (It seems to be done automatically), and I don't know how to check for carriage return. I am going to start researching this immediately but if you have a quick explanation I of course would appreciate it, since I might overcomplicate it independently.

Thank you again.

**Comment by hmatt843** [comment]
Thank you very much!! It turns out it was a 404 Error. LetsEncrypt was trying to visit the HTTP non-www version of my site, which I didn't have available, so I only had to make simple changes in my IIS and now everything is 'valid' and the certificate is working excellently, just like before! Your help is MUCH appreciated!

**Comment by ebekker** [comment]
Looks like you're all set, thanks @bseddon.

**Comment by hmatt843** [comment]
Hi, I'm sorry but I would really appreciate being given exact steps. I am having a hard time understanding what is really going on.

Like I said in the original post on this thread, I followed the steps in this video to a T (  from https://www.youtube.com/watch?v=SVUY7ygbGm8 ... I've also written the majority of those steps out in the original post here ) so I do successfully have a LetsEncrypt SSL certificate set up for "https://example.com". However, I still need help with the exact steps for getting https://**www**.example.com working, too.

I understand that I should be referring to this page: https://github.com/ebekker/ACMESharp/wiki/Quick-Start (Specifically, the 'Subject Alternate Name' section). However, this tutorial isn't crystal clear enough for me. I _think _it's saying the next command I should input in PowerShell (x86) is:

    New-ACMECertificate example.com -Generate -AlternativeIdentifierRefs www.example.com -Alias multiNameCert

But I am worried that if I try this, something will break because I don't know if I'm missing steps before or after this command, or if the command itself is even correct for my purpose. 

@bseddon did say "You will not be successful issuing the New-ACMECertificate command until you have issued the Complete-ACMEChallenge and Submit-ACMEChallenge and until the Update_ACMEIdentifier returns a valid challenge status for each alias dns1, dns2, dns3 and dns4."

But this leaves me with questions. Does this mean... "until you have issued the Complete-ACMEChallenge and Submit-ACMEChallenge" for dns1 (example.com, in my case), which I've already successfully done? Or does this mean something else?
I am also unsure if I need all four of dns1, dns2, dns3, and dns4 when I _think_ that example.com is dns1 and www.example.com is dns2, and it seems like those are the only two I need (so dns3 and dns4 seem unnecessary for my purposes? can someone confirm?). 

As you may guess, I am very much out of my field. I'm a newbie just trying to get LetsEncrypt working. I am honestly surprised I've gotten as far as I have with the certificate working for example.com .

**Comment by bseddon** [comment]
Sometimes when one has come to understand something, it's difficult to appreciate the comprehension difficulties of others.  That's my situation with your question so I apologise in advance if my comments cause any offence.

You seem to have a problem comprehending the importance of using aliases instead of domain names.  An alias is a concept used by ACMESharp to reference to a packet of information held about a specific domain.  The information held by ACMESharp is a copy of the information generated by the Let's Encrypt servers.

More than one alias can reference the same domain and can be used to generate different certificates for the same domain - its why there is no issue overwriting information.  For example, you will use a different alias for the same domain after 90 days when you need to regenerate a certificate.  Let's Encrypt certificates last only 90 days so they must be regenerated before then and using a new alias for an existing domain is a way to do this.

For a domain to appear in a certificate it must have been validated by LE.  That is, you must have successfully completed the steps up to and including Update-ACMEIdentifier for each alias that references a domain if that domain is to appear in a certificate.  If this were not true, then a hole would exist that would allow any domain (bbb.com) to be validated by a certificate just because one domain had validated (aaa.com).

So, to your questions.  You include this example command:

```New-ACMECertificate example.com -Generate -AlternativeIdentifierRefs www.example.com -Alias multiNameCert```

This will not work because 'example.com' and 'www.example.com' are not aliases, they are domains.  Given some of the other example commands you have provided, this command should be something like:

```New-ACMECertificate example.com_Alias -Generate -AlternativeIdentifierRefs www.example.com_Alias -Alias multiNameCert```

When I gave the example of 'dns1, dns2, dn3 and dns4' I did so to lean on the example on the quick start page hoping that by using this conceptual link it would reduce the risk of confusion.  That didn't happen.

dns1, dns2, dn3 and dns4 are supposed to represent arbitrary alias names. They could have been 'abc, def, ghi and jkl' or just 'abc' on its own. The term 'dns' has no meaning and is used on the quick start page to be a common prefix used by aliases for some putative real domain (example.com).  You are correct that there will be as many aliases in the list as you need for your scenario.

Nothing will be overwritten.  ACMESharp maintains a copy of the information held on the LE servers in it's vault.  If you issue a command that uses an existing alias ACMESharp will access the information already stored for that alias.  If you issue the command New-ACMEIdentifier for an alias that already exists you will get an error.

Likewise, if you try to generate a new certificate for an certificate alias that already exists you will get an error.  The certificates are also stored in the vault so when you issue an export command you are exporting from the vault.

If you look in the vault, are able to see a little bit of what's in ACMESharp black box.  You can find the location of the vault on your machine by issuing the command:

```(Get-ACMEVaultProfile).VaultParameters['RootPath']```

In this folder you will see a file called 00-Vault which is a file containing information in a JSON format.  It is a list of the aliases you have used (and details about those aliases),  The folders contain copies of various bits of information that are available on the LE servers relating to each alias you have used including the certificates you have generated.

**Comment by bseddon** [comment]
Try using the script I created: [Update-Certificate-http](https://github.com/ebekker/ACMESharp/issues/76#issuecomment-174705344)

I created this because I don't want to have to remember the command and because I want to be able to create a scheduled task that updates the generation of certificates automatically.  Assuming you've downloaded the script to a folder and that PowerShell current directory is that folder then the command will be something like;

```
$suffix = "-{0:D2}-{1:D2}-{2:D2}-2" -f [int](Get-Date).year,[int](Get-Date).month,[int](Get-Date).day
import-module .\Update-Certificate-Http.ps1
Update-Certificate-Http -alias "example$suffix" -domain "example.com" -websiteName "My Web Site" -domains @{"www.example.com$suffix"="www.example.com"} 
```

Obviously, your web site is not called 'My Web site' so this needs to be changed to be a valid IIS site name.  The command will generate a certificate for the domains example.com and www.example.com.  The aliases for each domain are made unique each time by the creation and use of a suffix based on the date.  That is, it will create a new identifier for each domain using the aliases suggested in the command and verify them.

The command command will then generate a certificate, using the validated aliases, that references both domains and load the generated certificate into the Windows certificate store.  Finally it will update IIS bindings for the domain to use the new certificate.

Even if you choose not to use the script, it will show you how the commands are to be used to accomplish your objective.

**Comment by hmatt843** [comment]
Thank you again. 
Before I try the script, I would like to attempt seeking help on what I /think/ is the last barrier here. If I have somehow gone in reverse on my progress then I won't blame you for giving up on me, lol.

Okay, so I first deleted the Vault folder and removed the certificate from my server to get a fresh start.

My understanding:
-one certificate can indeed multiple domains. 
-each domain that will be included in a certificate must be separately validated
-Therefore, I went through the validation process for each domain by doing the steps from

    New-ACMERegistration -Contacts mailto:myemail@gmail.com 
to
    Update-ACMEIdentifier -Ref example.com_Alias

until Update-ACMEIdentifier returned valid for example.com_Alias
and Update-ACMEIdentifier returned valid for www.example.com_Alias

So I have successfully achieved that -- they are both returning valid.

Now I am trying to create a certificate to include both of these. I've tried:
    New-ACMECertificate example.com_Alias -Generate -AlternativeIdentifierRefs www.example.com_Alias -Alias multiNameCert
and
    New-ACMECertificate example.com_Alias -Generate -AlternativeIdentifierRefs ([array]$('www.example.com_Alias')) -Alias multiNameCert
(note that I am including the quotation marks, like you clarified here: https://github.com/ebekker/ACMESharp/issues/104 )

and I even tried a user-suggested workaround:
    New-ACMECertificate example.com_Alias -Generate -AlternativeIdentifierRefs www.example.com_Alias,www.example.com_Alias -Alias multiNameCert

However, for each of these I get the error:

    New-ACMECertificate : A positional parameter cannot be found that accepts argument 'example.com_Alias'. 
    At line:1 char:1
    + New-ACMECertificate example.com_Alias -Generate -AlternativeIdentifierRefs www. ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo             : InvalidArgument: (:) [New-ACMECertificate], ParameterBindingException
        + FullyQualifiedErrorID    : PositionalParameterNotFound,ACMESharp,POSH.NewCertificate


So ... please let me know if I am doing something wrong that is obvious to you. Sorry for taking so much of your time. Also, no I was not offended by all by your explanation. It helped me a lot. I am a complete beginner to all of this and am starting to feel like I am comfortable with some concepts here.

**Comment by bseddon** [comment]
Well that is strange.  I've just run a command similar to the one you have run and it has been successful.  Below is the command and output.  As you can see the structure of the command is identical.

To be sure I'm running the same command as you, I pasted the exact command you listed above into the PowerShell window then replaced 'example.com_alias' with 'wordpress.wproute-2016-04-03-2' and 'www.example.com_alias' with 'wordpress.strongtyping-2016-04-03-2'.

```
PS C:\ACMESharp\Example> New-ACMECertificate wordpress.wproute-2016-04-03-2 -Generate -AlternativeIdentifierRefs wordpress.strongtyping-2016-04-03-2,wordpress.strongtyping-2016-04-03-2 -Alias multiNameCert


Id                       : b3d64322-394a-4212-86a0-9a0902bdf2cf
Alias                    : multiNameCert
Label                    : 
Memo                     : 
IdentifierRef            : 69d13b3b-bdbc-4adb-94fb-bb32da1daa01
IdentifierDns            : wordpress.wproute.com
AlternativeIdentifierDns : {wordpress.wproute.com, wordpress.strongtyping.com}
KeyPemFile               : 
CsrPemFile               : 
GenerateDetailsFile      : b3d64322-394a-4212-86a0-9a0902bdf2cf-gen.json
CertificateRequest       : 
CrtPemFile               : 
CrtDerFile               : 
IssuerSerialNumber       : 
SerialNumber             : 
Thumbprint               : 
Signature                : 
SignatureAlgorithm       : 
```

Since PowerShell is complaining about the positional parameter 'example.com_Alias' how about not using the positional parameter syntax.  The revised command would look like:

```
New-ACMECertificate -IdentifierRef example.com_Alias -Generate -AlternativeIdentifierRefs www.example.com_Alias,www.example.com_Alias -Alias multiNameCert
```

**Comment by hmatt843** [comment]
That's good news that it should work in theory. Still no luck for me, though --  http://imgur.com/cskdOZO.jpg 
you can see that I also tried your revised command but with "Identifier" instead of "IdentifierRef" just for the heck of it. I also tried it with the [array] version, which isn't pictured.

What used to work for me when I was just signing up for one domain was:

    New-ACMECertificate -Identifier example.com_Alias -Alias example.com_Certificate -Generate

so I'm not sure why that would work, but this won't.

**Comment by bseddon** [comment]
Sorry to hear of your problems.  What version of the software are you using?  The version number of the ACMESharp.POSH.dll file in my ACMESharp folder is 0.8.1.0. What it yours?

Both -identifier and -identifierRef should work because they are defined as synonyms in the software.  Have you picked up an older version that does not support some of the command parameters?

**Comment by hmatt843** [comment]
Whoops, yes, this is 0.7.1.0 I am working with. Changing course now!
