### ISSUE TITLE
Multidomain

### ISSUE THREAD

**Issue by MRTRALHA** [ebekker/ACMESharp#123]
Hello,

Can this library be used to generate multidomain certs? If so how? I cannot find any info in the wiki.

When i try to run :

New-ACMEIdentifier -Dns www.name.com,www.name2.com -Alias dns1

apparently -dns does not allow more than 1 argument
It doesn't work.

regards,
MRT

**Comment by jduncanator** [comment]
See the box titled "Subject Alternative Names (SAN)" under the [**Request and Retrieve the Certificate** section](https://github.com/ebekker/ACMESharp/wiki/Quick-Start#user-content-7-request-and-retrieve-the-certificate)

**Comment by MRTRALHA** [comment]
Ok. It works but when you have only 2 domains

You have to use:

New-ACMECertificate dns1 -Generate -AlternativeIdentifierRefs dns1,dns2 -Alias multiNameCert

As AlternativeIdentifierRefs does not allow only 1 content. It works! :-)

Please close it.

**Comment by MRTRALHA** [comment]
Closed :-)

**Comment by jduncanator** [comment]
By best practice a SAN certificate should *ALWAYS* have the Common Name included in its Alternative Names list. For example if you have www.example.com as your primary domain, use it in the Subject CN but also include it in the Alternative Name list. Some browsers will only use the Alternative Name list if it is present, so not including your primary domain could cause issues.

**Comment by netfed** [comment]
Am I doing something wrong, since I have done everything by the book in order to make a multi domain certificate. In the end I export (the three I made and combined) with this: Get-ACMECertificate multiNameCert -ExportPkcs12 "c:\certificates\multi.pfx". The effect of all this is that in IIS7.5, all the websites will use the same certificate as installed for the very first.

**Comment by jduncanator** [comment]
@netfed You can't use multiple certificates on the same IP in IIS 7.5, it doesn't support SNI. You'll need to assign different dedicated IP addresses to each site in order to specify a different certificate.

Alternatively, upgrade to a newer version of Windows/Windows Server and you'll get SNI support and can specify whatever certificate you want for any of your sites, all under the same IP address

**Comment by netfed** [comment]
@jduncanator : Thank you for clearing that up. I am quite certain that this will help a lot of folks out there that has come to this point in their experiments. A big boost came from Rick Strahl's website review of AcmeSharp. And then by the fact that Powershell IDE has the commands listed on the left side in the editor, which inspired to the investigation into parameters. F.ex. you can set a password for the certificate with the -CertificatePassword parameter. And finally, this problem's answer got me to search for indepth info. I learned that the Github project Wiki  is the place to start, in fact :-)
