### ISSUE TITLE
New-ACMERegistration: The underlying connection was closed: An unexpected error occurred on a receive.

### ISSUE THREAD

**Issue by jonthegiant** [ebekker/ACMESharp#124]
Following the quickstart guide here: https://github.com/ebekker/ACMESharp/wiki/Quick-Start
I successfully initialized a vault, but fail on 'New-ACMERegistration'

> PS C:\Users\XXXXXXXXX> New-ACMERegistration -Contacts mailto:XXXXX@XXXXXX.com -AcceptTos
> New-ACMERegistration : The underlying connection was closed: An unexpected error occurred on a receive.
> At line:1 char:1
> + New-ACMERegistration -Contacts mailto:XXXXXXX@XXXXXX.com -AcceptTos
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [New-ACMERegistration], WebException
>     + FullyQualifiedErrorId : System.Net.WebException,ACMESharp.POSH.NewRegistration

Event Viewer shows SCHANNEL errors at time of command execution:
```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Schannel" Guid="{1F678132-5938-4686-9FDC-C8FF68F15C85}" /> 
  <EventID>36871</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2016-04-15T14:55:22.160404700Z" /> 
  <EventRecordID>154897</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="704" ThreadID="5880" /> 
  <Channel>System</Channel> 
  <Computer>XXXXXXXXXXXXX</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="Type">client</Data> 
  <Data Name="ErrorState">10010</Data> 
  </EventData>
  </Event>
```

> This behavior is caused by the SMTP service processing an incoming EHLO command if no certificate is assigned to an SMTP site. This message is logged twice, once when the SMTP service starts, and once when the first EHLO command is received.

> This is an erroneous Event log entry. You can safely ignore this message. To prevent this Event log entry, you must assign a certificate to the SMTP site.

Okay... how am I supposed to do that if I have no certificates in the first place... Am I supposed to go the self signed route until LE issues me one?

https://technet.microsoft.com/en-us/library/dn786445.aspx#BKMK_36871

Windows Server 2008r2
Powershell v4
ACMESharp POSH v0.8.1.0

**Comment by jduncanator** [comment]
At the moment Let's Encrypt can't be used to directly sign certificates for servers other than HTTP servers using the default challenge type, this includes mail servers.

This can be solved by setting up a fake website under the domain for which you are running your mail server, say mail.example.com, and getting a certificate signed for it by Lets Encrypt following the normal certificate flow. Once you have your certificate you can then use it for your mail server running at mail.example.com. This works because SMTP over TLS and StartTLS use the same Key Usage values as a certificate used to protect a HTTP website.

Alternatively, ACMESharp also supports the DNS challenge type, which asks you to setup some TXT records in your DNS to prove ownership of the domain you are trying to generate a certificate for. Considering it seems like you won't be running a web server for the domain you are trying to setup, I would recommend using DNS authentication as it is much simpler and requires less work to get working.

On a side note, as far as I know, Lets Encrypt doesn't send an email when you create a new registration. The email supplied in the registration is used for renewal reminders. Due to this, you shouldn't need to create a self-signed certificate for your mail server (or even have it running yet) in order to get up and running for Let's Encrypt.

**Comment by jonthegiant** [comment]
Hi @jduncanator, thanks for your reply.
The SCHANNEL errors are generated every time I attempt to execute ```New-ACMERegistration```,
so to answer your question, yes, It happens every time I try to create a new registration.

The server in question is actually a web server. I can see how that may be confusing.

On a side note, I've successfully used ```letsencrypt-win-simple``` to generate a subdomain cert before, so I'm familiar with the process to an extent. 
I came here because of this: https://github.com/Lone-Coder/letsencrypt-win-simple/issues/205

**Comment by ebekker** [comment]
I'm not sure I follow how the event log message is related, the `New-ACMERegistration` just tries to issue a request to the LE server.  From the same host that you're getting this error on, can you issue the following and see what happens:

```PowerShell
Invoke-WebRequest -Uri https://acme-v01.api.letsencrypt.org/
```

Do you get a StatusCode=200 response with HTML Content?

I assume you're using the PROD Let's Encrypt service, not STAGE, correct?

**Comment by jonthegiant** [comment]
Meant to close this with a comment:
Server in question is being wiped, out of my control, sorry to waste your time guys. Thanks for your responses @jduncanator and @ebekker

**Comment by embj** [comment]
I realize this is an old thread, but I ran into this tonight after recently running a script to lockdown my protocols and ciphers. Running Server 2016 Core and also couldn't do an Invoke-WebRequest successfully to any website.

I completely undid all of the changes made by the script and stepped through each section one-by-one...turns out that disabling TLS 1.0 is what triggered the issue. Apparently, .NET Framework 4 is not set to use TLS 1.1/1.2 out of the box. 

In order to enable PS/.NET 4 apps to use TLS 1.1/1.2, you need to set the following two reg keys: 
New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 -Name SchUseStrongCrypto -Type DWORD -Value 1
New-ItemProperty -Path HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319 -Name SchUseStrongCrypto -Type DWORD -Value 1

Hope this helps anyone else that may stumble upon this issue. Took me a couple of hours to work through it and find the solution.

**Comment by genodeftest** [comment]
@embj: This is a very helpful advice. Thank you very much!

Who would expect that any software in 2018 is still not ready for running a basic communication technology just *recently* introduced (2006)…
