### ISSUE TITLE
Cloudflare DNS provider?

### ISSUE THREAD

**Issue by ShaRose** [ebekker/ACMESharp#138]
Would you be able to add a provider using the Cloudflare API to solve DNS challenges, similar to the one used for Route53?

**Comment by bseddon** [comment]
I suspect you are not getting a response because unless someone uses Cloudflare, their ability to code to the API is not possible.  Have you considered doing this yourself and submitting a pull request?

**Comment by qgustavor** [comment]
@bseddon I use CloudFlare and tried their API once. I don't know C#, so I can't write a provider, but I found [an Python script](https://github.com/kappataumu/letsencrypt-cloudflare-hook/blob/master/hook.py) which handles DNS challenges which CloudFlare. Here is how it works:

* As in the documentation "The CloudFlare API is a RESTful API based on HTTPS requests and JSON responses". Two parameters are required in all requests for authentication: `X-Auth-Email`, the email used to log in, and `X-Auth-Key`, which can be obtained in the "My Account" page.
* In order to change DNS records for Let's Encrypt first get the zone identifier for the domain using the [/zones](https://api.cloudflare.com/#zone-list-zones) endpoint, where zones are listed.
* Get the DNS records for this zone in the [/zones/:zone_identifier/dns_records](https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records) endpoint.
* If the Let's Encrypt TXT record exists then [modify it](https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record), if not [create one](https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record).
* Wait and check for propagation (using DNS lookups) then send submit the challenge response.

**Comment by ebekker** [comment]
I think this would be a great addition -- CloudFlare offers a free tier of service, but I'm not sure if that includes access to their API for supporting this.  If so, someone should be able to develop something fairly quickly and easily using the AWS provider as an example.

A PR to add this as a provider would be welcome.

**Comment by oliverrahner** [comment]
API access is included in their free service! I did just what the OP asked. But, to be honest, I did it quite quick & dirty in POSH. I haven't noticed the concept of providers until reading this request.

Maybe I could look at it in the next days and then create a provider for Cloudflare and one for EuroDNS.

**Comment by ebekker** [comment]
Great!  @oliverrahner a good place to start that would be comparable to what is already there would be the AWS Route53 provider which can be found in [this project](https://github.com/ebekker/ACMESharp/tree/master/ACMESharp/ACMESharp.Providers.AWS).  The {{ChallengeHandlerProvider}} and {{ChallengeHandler}} are the key starting points for implementing a provider.

**Comment by janpieterz** [comment]
I've been playing around with this and have just done a successful verification using CloudFlare DNS. There's still some work to be done (unit testing, fault paths) etc. Has anyone started working on this yet? If not I can push the code and we can discuss some details on the fork.

**Comment by ebekker** [comment]
PR #175 adds support for CloudFlare, thanks @janpieterz!
