### ISSUE TITLE
Is renewal ignoring AlternativeIdentifierDns?

### ISSUE THREAD

**Issue by canoas** [ebekker/ACMESharp#143]
has anyone used renewal of a multi alias cert? did it work for you?

I'm using https://github.com/webprofusion/Certify/issues/3 - maybe the problem is in the UI.

**Comment by ebekker** [comment]
ACMESharp does not yet support the official renewal mechanism that is built into the ACME protocol, the only way to renew now is to re-request a new certificate based on the already validated Identifiers (DNS names), so that mechanism works the same way whether you're requesting a cert for the first time, second time or any time thereafter.

I'm not sure if Certify is doing anything fancy on that front, but most likely the fix will be there for the current renewal support.
