### ISSUE TITLE
LE Server IP Range

### ISSUE THREAD

**Issue by gargricha01** [ebekker/ACMESharp#157]
Hello,
When requesting for a certificate from LE server, the agent must be pointing to certain IP range for LE server. We understand that the request is made over port 443 but we need to know the specific destination addresses for LE server as we can't open the FW port with 'Any' as destination. Could you please help me on this. Thanks.

**Comment by ebekker** [comment]
Unfortunately, this isn't anything I can help with -- and on the LE [FAQ|https://letsencrypt.org/docs/faq/] (last question) they explicitly state they don't publish their IP address range.

If you're looking to whitelist *outgoing* HTTPS traffic (i.e. from the ACMESharp client to LE servers), then you can look into whitelisting by HTTP domain name through an approved Proxy (such as HAProxy) or many others -- your org may already have on in place.  If this is not an option, then you are pby not a good candidate for using the LE service.

If you're looking to whitelist *incoming* HTTP traffic from LE servers to validate your server, then instead of doing the HTTP Challenge validation, you can use the DNS validation.
