### ISSUE TITLE
How to handle proper copyright attribution?

### ISSUE THREAD

**Issue by ebekker** [ebekker/ACMESharp#173]
The majority of the ACMESharp codebase has been written by myself, and while there have been several contributions from the community here and there (much appreciated!), they've mostly been just code fragments and snippets that adjust the existing code base...until now.

A few contributors have submitted PRs that help enhance and extend the feature set of ACMESharp with new code and modules.  Up until now I have been assigning copyright notice to myself, but with these changes I think it's time to evaluate and establish a policy that will properly credit and attribute the respective contributors.

I'm not looking to break new ground here, this _must_ be an issue that has been dealt with and addressed by just about every other OSS project, so I'm just looking to identify a few good examples that we should follow and this ticket will serve to document that process.

CC:
- @ftoyon
- @janpieterz
- @michaelfdeberry
- @bseddon
- @rkerber
- @Lone-Coder

**Comment by ebekker** [comment]
Some good prior discussions out there:
* https://github.com/flycheck/flycheck/issues/649
* http://softwareengineering.stackexchange.com/a/158011
* http://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/
* https://www.quora.com/How-do-I-properly-credit-an-original-codes-developer-for-her-open-source-contribution
* https://carto.com/contributing/

Hmm, should ACMESharp establish a CLA?

**Comment by bseddon** [comment]
My thought is that you are trying to be too accommodating.  Perhaps if someone is contributing a major beneficial change maybe based on years of their own work, then there is an conversation to be had with you.  But I'd be happy signing over copyright of a contribution.  If you are offering a credit, that's nice but not really necessary.

I put a script out there and it includes a copyright to me.  But that's because you are supposed to include a copyright and in the absence of any other instruction I don't know what else to do.  Also, its a standalone thing.  But in principle, I have no problem transferring the copyright if that's a direction you would choose to go.

I've occasionally contributed to other projects - WordPress or a WordPress plugin called Easy Digital Downloads or XDebug .  These project require that copyright to contributions is transferred to the project and you have to declare that code is not copyright of anyone else.  This makes sense because users want to know they are not entering a copyright labyrinth.

If you have copyright of contributed code I think you also inherit an obligation, for example for maintenance.  When contributors make updates to WordPress, the WordPress team takes on the responsibility for maintenance, translation (if needed) and so on of that contribution.

Maybe you don't want this responsibility.  I can understand that.  It's hard enough remembering your own code.  Learning someone else's code can be tough.

**Comment by ebekker** [comment]
@bseddon, thanks for the feedback -- I think I'm going to follow your suggestion.  It doesn't appear anyone else has any strong feelings about it either way, so I expect there won't be any contention in adopting this approach.

I'll be setting up a system similar to other OSS projects that require a CLA acceptance which include transfer of the copyright ownership.

Thanks!
