### ISSUE TITLE
DISCUSS:  Can we break out the Vault and related APIs from POSH to be usable by other code?

### ISSUE THREAD

**Issue by ebekker** [ebekker/ACMESharp#20]
It seems there might some value in decoupling the Vault concept and related API from the POSH module as discussed in #12 such as [this comment](https://github.com/ebekker/letsencrypt-win/issues/12#issuecomment-154910658).

If we want to isolate the Vault as a common entity that can be leveraged by multiple clients, we would need to pull it out into its own assembly from the POSH stuff.  Also we'll have to refine the API to make use of more well-defined and standardized constructs such as the different assets.

Right now the Vault treats all of these as opaque and only provides facilities to tag them as a specific logical type.  But if we're want two different clients to understand the content of a Vault, they need to use a standard format for all the elements contained within.

**Comment by ebekker** [comment]
@webprofusion-chrisc, @Lone-Coder

At this point, I'm looking to discuss this idea.  You two seemed to have the most interest in this idea for now as far as other clients/tools that might make use of this.

**Comment by webprofusion-chrisc** [comment]
Yes this would be great and would make the distinction between the ACME client code and the Vault clearer. The Vault is a great idea (a registry of the results from working with the ACME client) and can be extended to include other management info not strictly related to the ACME client. I would also suggest that we allow extendable configuration as Key Value pairs, so that clients with different feature sets can inter-operate on the same vault without having to make changes to the vault Schema.

With that said, my work-in-progress GUI actually uses the Powershell scripts to perform most of it's tasks. It can optionally init a vault, take any domain name and run a manual HTTP Provider based challenge to the point where we have a pfk file to import into IIS. Currently it has a manual step for copying the challenge response file into wwwroot.

Long term your Vault may come from a database store (or multiple stores) rather than a file store. I can imagine if you have hundreds of domains and subdomains on multiple servers each with a 90 days expiry, management of those certs and keeping them current is quickly going to be a problem that requires an easy solution.

**Comment by ebekker** [comment]
Yep, the non-file-based Vault is already [on the drawing board](../7).  In fact some of the changes I made recently to add support for assets was to make that a possibility.  And I always had it in the back of my head that I wanted to do something like that -- it's one way to centralize the registry of all the certs an org may issue, especially if it's across lots of different servers.

Also, with the 90-day expiry, the only way that I can see that being manageable is to have an automation piece that just runs in the background.

Glad to hear the GUI is working through the POSH interface, that will be a good test of the module.  Regarding your manual step -- not sure if you saw but I recently added a new Web Server challenge handler that handles this typical case.  It's similar to the Manual provider in that it's essentially file copy oriented, but it takes care of a lot of the details that a typical user would need to do by hand with the Manual provider.

**Comment by Lone-Coder** [comment]
I'd like to keep the CLI client as simple as possible and only store the minimum required to disk, both for security and simplicity. That might make the use case for the vault different enough that it wouldn't make the work of pulling the vault code out of POSH of any value.

Am I going to need to save as extensively to disk as POSH does or will I be able to avoid doing that as much since calling the CLI is a longer running operation that just keeps the data in memory as objects? I've not looked yet at what's going to be needed for renew/revoke operations.

Just checked and looks like the POSH client doesn't handle renew/revoke either. Is renew just getting a new cert or is it something different?

**Comment by Lone-Coder** [comment]
I started working on saving registrations, signer, authorizations, etc.

I just discovered that authorizations have an expiration of 10 months.

From a production server auth:
  "Status": "valid",
  "Expires": "2016-09-06T18:33:06Z",

So that means that we'll need to do auths again for automated renewals. Since we have to do that anyways, there's not much benefit in saving anything but settings to disk. We can re-register and re-auth for each renewal and not worry about securing the registration key.

**Comment by Lone-Coder** [comment]
Seems like the settings should be stored in the registry. Most complex part would be the certs that need renewal.

**Comment by ebekker** [comment]
I believe that any client will need to store permanently the same set of details that the POSH client, I'm currently storing a very slim set of information that's needed to complete and end-to-end scenario to get a certificate, plus some additional provider config data needed to support the different challenge handlers and server *configurators*.  If the CLI client is very narrow in what scenarios it will support, which is perfectly legit, then there are some elements that you won't need to worry about.

It's true that you can simply throw away most of the details because you can regenerate them any time you want since all of this is essentially free and there's no cost do doing so, however there are some considerations to be aware of.  First, LE is intending to start off with 90-day certs, and they recommend that users renew every 60 days just to be safe and include ample overlap.  To do this you need to at least keep track of your reg and some related details (private key, public key, Reg URI, recoveryKey if you want to support that, and perhaps some of the other URIs if you intend on allowing access to that info like AuthzUri, TosUri, CertsUri).

LE is imposing a limit on the number of unique and new registrations they allow per IP.  During the testing period it's 10, and they said they will pby increase it after launch, but it will most likely not be infinite, that may generate too much waste in their DB.  If you regen every 60 days, you can quickly hit that limit, especially if you're securing multiple servers behind the same IP address.

If you intend to support renewal and revocation, then you also need to store some details about issued certs (cert URL) since those operations are done disconnected from the original cert request and at a much later time.

Also, if you're supporting any Identifer Challenge types that can be completed *out-of-band* with the original cert request, then you need to store Identifer validation state so that you can resume the challenge handling and submit it for validation, for example if you allow manual handling by the user.  If you only support challenge handling that is implemented within the CLI client itself, then you don't need to worry about this as it can all be kept in-proc/in-memory.

Also, if you want to support the "Key Authorizations" challenge type, you'll need to store and retrieve state info about prior keys, if you don't support it, not an issue.

**Comment by Lone-Coder** [comment]
Thanks for all the info.

The reg rate limit is 10/ip address *per day*. So it won't be a problem for
renewals, but I did run into it when developing initially.

I've started working on storing enough info to renew and am wrapping the
settings in a class that you might be able to reuse.

**Comment by ebekker** [comment]
Ah, good call -- I totally missed that it was a daily limit.  I guess in practice this could still be an annoyance for a large number of servers at a single site or data center, but pby not an issue after the beta.

**Comment by ebekker** [comment]
This was completed as part of the change for cleaning up the providers model.

See the [release announcement](https://groups.google.com/d/topic/acmesharp/sPYPFwPVQ5Y/discussion) for more details.

Please note, discussions should now be posted to the [community forums](http://groups.google.com/group/acmesharp).
