### ISSUE TITLE
Initialize-ACMEVault 

### ISSUE THREAD

**Issue by RuiHanDong** [ebekker/ACMESharp#207]
![image](https://cloud.githubusercontent.com/assets/20202350/22019200/6ec72286-dced-11e6-9b2c-8a9d08fdaf1f.png)

PS C:\Program Files (x86)\PowerShell\6.0.0.14> Initialize-ACMEVault
Initialize-ACMEVault : The type initializer for 'ACMESharp.POSH.InitializeVault
' threw an exception.
At line:1 char:1
+ Initialize-ACMEVault
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Initialize-ACMEVault], TypeIn
   itializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,ACMESharp.POS
   H.InitializeVault

**Comment by ebekker** [comment]
Are you trying to run this with PowerShell v6?  That's not supported.

**Comment by RuiHanDong** [comment]
Which version of PowerShell  is more suitable for ACMESharp??

**Comment by RuiHanDong** [comment]
thanks

**Comment by ebekker** [comment]
FYI, the current version of ACMESharp is based on Windows-based PowerShell and should work with PowerShell versions 3.x - 5.x.  This is based on .NET Framework (i.e. the full/classic version of .NET that is Windows-specific).

PowerShell v6 is still in early stages (alpha or pre-alpha) but it is based on .NET Core.  I do plan on supporting this version eventually, but because it is still in early stages and lots of things are changing frequently, this does not have a high priority right now.  However, some *very preliminary* work on this new version [has already been started](https://github.com/PKISharp/core).

**Comment by vladox** [comment]
Hi @ebekker 
How is the implementation in .NET Core coming along? Are you accepting collaborators?
