### ISSUE TITLE
 Submit-ACMEChallenge  error:challenge has not been decoded

### ISSUE THREAD

**Issue by RuiHanDong** [ebekker/ACMESharp#210]
![image](https://cloud.githubusercontent.com/assets/20202350/22057117/46997c12-dd9e-11e6-84f9-23162c7820e4.png)
PS C:\Windows\system32>  Submit-ACMEChallenge dns2 -ChallengeType http-01
Submit-ACMEChallenge : challenge has not been decoded
At line:1 char:2
+  Submit-ACMEChallenge dns2 -ChallengeType http-01
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Submit-ACMEChallenge], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,ACMESharp.POSH.SubmitChallenge

**Comment by WallyRanson** [comment]
I have run into that error a couple of times too.
My script tries to validate like 12-15 different FQDNs for a SAN certificate and this one just occurs out of the blue.
By me it occuring in this way.
My script i s following the Quick Start Guide (https://github.com/ebekker/ACMESharp/wiki/Quick-Start) and runs untill section 6 where everything is looking fine.
Then at section 6b I check for the status change, but nothing happens.
I have waited for almost 24 hours without any change.
Then when I redo section 6 I receive this error.

So far it has not been a specific FQDN that causing it and my solution has been  to wait for the update for 5 minutes and if no change has been detected, then simply start over from section 4 again.
Its rare that the error occur again right away and since its a script that is running fully automated, then it can not be and error in the command lines.
My conclusion was that it was an error at Let's Encrypt's end.

**Comment by ebekker** [comment]
Since you're submitting the challenge, I assume that you have already completed it (with `Complete-ACMEChallenge`), correct?

If so, can you try running `Update-ACMEIdentifier -IdentifierRef dns2` and then try to submit it again?

If you still get this same error, try forcing it to complete the challenge again using `Complete-ACMEChallenge` but adding the following two switches `-Regenerate -Repeat`.  Then trying submitting it again.

Let me know if either of those work.

**Comment by WallyRanson** [comment]
I do not have the error at the moment, but I tried to resubmit when I had it and that changed the status immediately from pending to invalid.
Maybe RuiHanDong can help more. :)

**Comment by RuiHanDong** [comment]
![image](https://cloud.githubusercontent.com/assets/20202350/22089547/d1d69e26-de26-11e6-8c7c-88fad11fdabc.png)
![image](https://cloud.githubusercontent.com/assets/20202350/22089599/32d53246-de27-11e6-9efa-63f47bfbe689.png)

{
  "identifier": {
    "type": "dns",
    "value": "crtata.cn"
  },
  "status": "invalid",
  "expires": "2017-01-25T06:51:50Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/T_14advi9CJ75hRuL4OaaAQ12r6RkElBfXKgvc99Ktg/513970983",
      "token": "Zmfac8jp4OHtA8isNTElxZ4LZKp1EDYj-xDAK3v4JuE"
    },
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:connection",
        "detail": "DNS problem: NXDOMAIN looking up A for crtata.cn",
        "status": 400
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/T_14advi9CJ75hRuL4OaaAQ12r6RkElBfXKgvc99Ktg/513970984",
      "token": "cSZXZlCPbBkysnSrrqnPGrVLPLmOGDZd4xiHr_o3bkI",
      "keyAuthorization": "cSZXZlCPbBkysnSrrqnPGrVLPLmOGDZd4xiHr_o3bkI.uAZ4-HrWFuto-zf0vAUNcVXaizG5BgnsURL8VoHUo08",
      "validationRecord": [
        {
          "url": "http://crtata.cn/.well-known/acme-challenge/cSZXZlCPbBkysnSrrqnPGrVLPLmOGDZd4xiHr_o3bkI",
          "hostname": "crtata.cn",
          "port": "80",
          "addressesResolved": null,
          "addressUsed": ""
        }
      ]
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/T_14advi9CJ75hRuL4OaaAQ12r6RkElBfXKgvc99Ktg/513970985",
      "token": "hFp-F2z1biRnNbrMX7HnNLBlMsYgHUi_5sjfReGuVss"
    }
  ],
  "combinations": [
    [
      1
    ],
    [
      0
    ],
    [
      2
    ]
  ]
}

**Comment by ebekker** [comment]
OK, so you're using the *manual* HTTP challenge handler -- I didn't see you mention it anywhere in your comments, but I *assume* you are taking the info that's printed out by the manual challenge handler and manually applying it to your site, correct?

And then that site needs to be reachable by Let's Encrypt's servers to validate the DNS Identifier.  I tested out the specific DNS name you have in the screenshots above `crtata.cn` and IP doesn't even resolve for me, so it pby won't work for LE either.

**Comment by RuiHanDong** [comment]
thanks for ebekker . the error of submit has been solved .but Error in the  following steps  .
![image](https://cloud.githubusercontent.com/assets/20202350/22090966/3b99b566-de2f-11e6-834c-0d00fdd1bb83.png)
![image](https://cloud.githubusercontent.com/assets/20202350/22090985/5920e474-de2f-11e6-8b72-0e79af93c8f7.png)

**Comment by ebekker** [comment]
The Issuer certificate is missing,  you have to use `Update-ACMECertificate` to fetch it

**Comment by alexhass** [comment]
> Complete-ACMEChallenge : Parameter cannot be processed because the parameter name 'Repeat' is ambiguous. Possible matches include: -RepeatDecoder -RepeatHandler.

and now?

**Comment by mahaveerrathor** [comment]
Complete-ACMEChallenge : Parameter cannot be processed because the parameter name 'Repeat' is ambiguous. Possible matches include: -RepeatDecoder -RepeatHandler.

and now?

=> Go with  -RepeatDecoder
