### ISSUE TITLE
Question about DnsAlias and CertAlias entities and either one of them is redundant now

### ISSUE THREAD

**Issue by centur** [ebekker/ACMESharp#215]
I have a question about two entities which are a bit tricky to grasp in ACMESharp terminology. Also I checked quick start and they both present there (`dns1` and `certAlias`) so I assume this is still valid concepts:

`Dns Alias` - when we creating new ACMEIdentifier we are using Dns Alias e.g. :

```
$dateSuffix = Get-Date -format "yyyy-MMM-dd_HH-mm"
$DomainName = "example.com" # this is the domain record we want to generate certificate for
# dns1 from QuickStart
$DnsAlias = "$DomainName-$dateSuffix"   

New-ACMEIdentifier -Dns $DomainName -Alias $DnsAlias
#...
```

Is this an alias that belong to Lets Encrypt domain e.g. it's submitted to LE-API and used for all consequent submissions\requests there ? If yes - this concept should stay (and maybe get some clarification in purpose)

Then there is a concept of Cert Alias which is introduced in `New-ACMECertificate` cmdlet which is used in consequent submissions: 
```
New-ACMECertificate dns1 -Generate -AlternativeIdentifierRefs dns2,dns3,dns4 -Alias multiNameCert
PS> Submit-ACMECertificate multiNameCert
```

Is this a concept that is used only by ACMESharp to have a nice named reference to a particular certificate request submission or it's somehow used in the submission to the LE-API and must be kept as well ?

Given that the Authorization for a domain is now short-living (shorter than an issued cert lifetime) - would it make sense to simplify ACMESharp names and parameters - it's pretty reasonable to add timestamp to the DnsAlias automatically during submission and then use same unique DnsAlias as CertAlias identifier ? 

It feels that this entire concept of "domains -> domain identifiers -> certificate identifiers" can be simplified a bit (unless this is what LE want to see submitted in API) as we really have to keep unique domains in the vault and then generate new unique DomainIdentifier (which is domain+timestamp) every time. 

Then we can have 1-1 relationship with `DomainIdentifier` and `CertificateIdentifier` - which means we can use one value (DomainIdentifier) everywhere and deprecate `CertificateIdentifier` concept 

This is possible because once Cert is successfully generated - next attempt may occur much later than DomainIdentfier Authorization expires, thus implies a new DomainIdentifier generation and new challenge completion. Previously it made  sense to avoid vault cluttering with aliases but now it's hard to make vault entries tidy as we need to submit new Authorization on cert re-issuing after 60 days.

Thoughts ?

**Comment by bseddon** [comment]
A 'dns alias' is a short hand that ACMESharp uses to associate the domain being verified and the keys exchanged with the LE servers to validate the verification request steps.  As you know, the ACME protocol (ACME is the name of the LE protocol) requires several steps to verify a domain and the keys are used to verify the same entity is performing each step.

A certificate request can include *multiple* 'dns alias' instances.  If the 'cert alias' and the 'dns alias' are the same this will not be possible.

So the LE process makes a distinction between the action of verifying a domain ('dns alias') and the action of requesting a certificate ('cert alias') for one or more verified domains ('dns alias').

I hope I have not missed your point.

**Comment by centur** [comment]
Well, I'm not sure I groked the necessary relationship between CertificateIdentifier and DomainIdentifier from this explanation. Re-phrasing the initial concept:

1. It's possible to create and validate multi-domain certificate by generating fresh and new DomainIdentifiers every time. Each domain identified can have an equally unique CertificateIdentifier (in my case they are equal)

2. For me it seems that if we can work with the system and have 2 entities (domainID and certID) always equal to eachother - one of them is redundant.

3. Previously there was a reason for keeping old domainIds and using them in cert reissuing: e.g. we didn't need to confirm and re-confirm domain ownership to generate a new cert after 2-3-5 months. so one can include OLD DomainId in the new CertRequest as a SAN domain (I've reused my 2nd level domain entries when generated 3rd level domain certs, so one cert has both - domain and subdomain - simplifies things a bit)

4. The case in p3 is no longer valid as one need to re-confirm the ownership of the domain with new challenges every time (lifespan of valid confirmation is shorter than a lifespan of a cert so one need to re-validate all the time)

NB: I may not understand all the consequences of my approach as it seems that I'm cluttering my LE profile record with multiple certificateIdentifies for the same set of domains. But I'm not sure I fully understand the relationship between all these identifies and what can be safely reused in automated scripts and what's not, the current domain terminology is keep blewing my mind :( ...

**Comment by ebekker** [comment]
(1) true
(2) this is only true if each Domain Identifer is equal to one and exactly one Certificate Identifier -- that is not the case.  You can request multiple certs for the same Domain Identifier, for example, if you want to generate distinct certs for different servers in a Web Farm.  Also, if you are create a SAN certificate, i.e. a single certificate which can have up to 100 alternative DNS names on it, then you will have up to 100 Domain Identifiers, and only a single Certificate Identifier.
(3) true
(4) only partly true, the *lifetime* of a Domain Identifier has been shortened from several months to a few days, but within that span of days, you can issue multiple certs under the same Identifier

The ACME protocol (and thus LE) defines a number of *entities* that are involved in the process, such as Registrations, Identifiers (aka Domains), Authorizations, Challenges and Certificates.  The ACMESharp library and PS module just tack on a few elements on top of those basic constructs to help manage the whole process and make the individual instances more easily *addressable*.

The ACMESharp PS module does not try to hide or even necessarily simplify the overall process steps.  That's by design -- it's the most basic tool to complete the process, but because it's PS, it can be fairly easily scriptable to put the pieces together any way you want, and a few folks have already done this (please see the [contributions](https://github.com/ebekker/ACMESharp/wiki/Contributions)).

Further, you can avoid PS altogether and construct a client that's as simple or as powerful to use as needed, and again a few folks have done that already as well (see Contributions).

**Comment by centur** [comment]
This is a great explanation, thank you. I was under impression that domain identifier is mostly a short name for the records in vault, and IIRC vault is ACMESharp way of storing data (so it's not mandated by ACME protocol).
Out of all these - I think I'm pretty happy with a new setup we had - 1 domain identifier -> 1 Cert Identifier (fewer moving parts and overal much cleaner script), they are unique and timestamped. 

Just need to write something to prune old domain identifiers from my vault.
 😄 👍

**Comment by ebekker** [comment]
Sounds like you're in good shape now.
