### ISSUE TITLE
New-ACMECertificate from CSR without Private Key

### ISSUE THREAD

**Issue by AzCii** [ebekker/ACMESharp#221]
I'm quite new to ACMESharp and Let's Encrypt in general.
I have an java application that have generated a csr.pem file for me, when validating the file using Symantec CryptoReport, everything looks fine.

I have not been able to sign the CSR using ACME, because it wants a key.csr.pem, which i don't have. 

Are there a way to either run the command only using the csr.pem, or maybe a way to generate the key.pem neede?

This might be due to a lack of understanding of SSL, or me just misunderstanding how this command is supposed to work.

This is what i have tried (as i can't specify CsrPemFile without KeyPemFile):
```
New-ACMECertificate -IdentifierRef dns1 -KeyPemFile "certificate.csr.pem" -CsrPemFile "certificate.csr.pem" -Alias cert1
Submit-ACMECertificate cert1
```

But this returns:
```
Submit-ACMECertificate : Error parsing certificate request. Extensions in the CSR marked critical can cause this error: https://github.com/letsencrypt/boulder/issues/565
At line:1 char:1
+ Submit-ACMECertificate cert3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (ACMESharp.Vault.Model.CertificateInfo:CertificateInfo) [Submit-ACMECertificate], AcmeWebException
    + FullyQualifiedErrorId : urn:acme:error:malformed (400),ACMESharp.POSH.SubmitCertificate
```

**Comment by WallyRanson** [comment]
Look at step 8 Quick Start in WIKI link at the top on this page.

**Comment by AzCii** [comment]
Step 8 descripes how to export a Private Key from a certificate, not from a request, I can't get past step 7, as New-ACMECertificate don't seem to accept CsrPemFile without KeyPemFile.

Normally i would not expect the CA to require me to sent them my Private Key together with the request.

**Comment by WallyRanson** [comment]
From the FAQ:

How do I use my own custom CSR, with my org and other certificate information? The cmdlet that's used to start a new certificate request (New-ACMESharp) can be used to either generate all the required initial assets or can import existing ones that you have generated outside of ACMESharp (i.e. using OpenSSL, Windows CA, Java Keystore, Bouncy Castle, etc.). There are two assets that are required, a private key file (for example for RSA-based certificate, you would need an RSA private key) and a Certificate Signing Request (CSR). Both of these need to be available in the PEM-encoding format and then you would provide these using the cmdlet parameters -KeyPemFile and -CsrPemFile respectively. See this issue for more details.

You need to get both of those informations from the Java application.
These two files are interconnected. One is used for encrypting and the other for decrypting.
They are made as part of the same process and the process is made, so that its pretty much impossible to recreate exactly the same set of files again, which is the basic of encrypting, ie. making it practically impossible to recreate, but not theoretically impossible.

If its possible to tell what java application you are using, then maybe we can help with that. :)

**Comment by AzCii** [comment]
Normally when i have created new certificates, I have never shared the Private Key with the CA, I'm sure the key is hidden somewhere in the application, I have asked the developers for assistance to find it, but no luck so far.

The application in question is "Ubiquiti UniFi Controller" for Windows.
I'm following this guide to for the SSL part: [https://help.ubnt.com/hc/en-us/articles/212500127-UniFi-SSL-certificate-error-upon-opening-controller-page](https://help.ubnt.com/hc/en-us/articles/212500127-UniFi-SSL-certificate-error-upon-opening-controller-page)

**Comment by WallyRanson** [comment]
Can this be used?
https://community.ubnt.com/t5/UniFi-Wireless/UniFi-Server-HTTPS-Certificate/td-p/338040

**Comment by AzCii** [comment]
It looks like that's working after a couple of tweaks, but i just ran in to the certificate rate limit for my domain, so was unable to complete my tests.

I'm on my 3rd supporter from Ubiquiti and they have still not been able to tell me how certificate changes is supposed to work with their software.

**Comment by fpeterson194** [comment]
AzCii,
I´m currently testing the same as you. If you use the -CsrDetails parameter you need to specify the private key file and csr file. Why the private key? My guess is because you need to decipher the ACME challenge that CA sends to you. The CA will use the public key embeded within the CSR in order to validate you own the domain you want to register. I´m pretty sure it does not send your private key to the CA (I didn´t check the whole code yet), it just use it for the challenge.

If you want to use -CsrDetails and use the ACMESharp to generate a keypair for you (private/public key) you should execute something like this:

New-ACMEIdentifier -Dns $FQDN -Alias $FQDN -CsrDetails @{ Country =""; StateOrProvince =""; Locality = ""; Organization = ""; OrganizationUnit = ""; Description = "" }
Submit-ACMECertificate cert1

There you can fill the CSR details manually and the keys should be created automatically. I´m testing it too. I will let you know my feedback when I have time. Let me know if this helps :)

**Comment by ebekker** [comment]
ACMESharp doesn't send the private key to Let's Encrypt, but it requires you to provide it so that it can "store" it in the vault alongside your CSR and eventually your CRT (when it's issused by LE).  In order to use a PKI certificate, you need 2 components a private key and public certificate.

When a Public cert is issued by a CA (like LE), you generate a private key and a CSR that is *signed* by the private key.  If your Java application generated a CSR file but didn't also spit out a private key file, it's possible it could be combined into a single PEM file (though this is unusual).  You can open a PEM file in a text editor (it's a plain text file with base64-encoded data demarcated by `--BEGIN...--` and `--END...--` blocks.  If your PEM file contains both the key and the CSR, I would suggest you split them out, you can do this manually since it's just a text file and save the file as a key and erase everything that is not the key, and a CSR and erase everything that is not the CSR.

HOWEVER -- this is just a suggestion and not required.  If the same single file, contains both parts (private key and CSR) you can just simply specify the same file twice to ACMESharp when providing your own PKI components.

**Comment by AzCii** [comment]
The CSR file from Unifi does not contain a key i'm afraid, still waiting to hear back from if this is by design or not.

But would it not be possible to just generate the Key on the fly and then use that, if only a CSR file is specified?
I'm asking because I have not provided a KEY to my CSR file when i have requested a certificate from GoDaddy or Symatec in the past, so this must be possible.

That said, the "hack" provided by WallyRanson , did solve my issue, so i'm not sure if you just want me to close it here, or if you want to look into generating the key if none is provided.

**Comment by ThomasCr** [comment]
hmm.. in UniFi Controller you can import the whole cert (private key and public cert)
see https://community.ubnt.com/t5/UniFi-Wireless/Your-own-SSL-key-and-cert/td-p/285508

**Comment by ebekker** [comment]
I'm not sure how you can have a key and a CSR that are not "connected".  If you provide a CSR without a key, they will not be "associated" so there's no point.

This seems like a very peculiar and particular scenario.  If you are satisfied that your situation is resolved, please do close the ticket.

**Comment by AzCii** [comment]
Yes, I got a solution that worked for me, so i think Its Okay to close this here.

Thank you All for your assistance
