### ISSUE TITLE
Using CSR with SAN

### ISSUE THREAD

**Issue by fpeterson194** [ebekker/ACMESharp#223]
I´m currently using the parameter -CsrDetails in order to put more information on the certificate.
By taking a look here (extracted from issue #191 )https://github.com/ebekker/ACMESharp/blob/master/ACMESharp/ACMESharp/PKI/CsrDetails.cs
You have the parameter "AlternativeNames". I have the following questions:

1.If I want to register domain NAME1 that has 10 SAN, I assume I cannot do the following:
New-ACMEIdentifier -Dns $NAME1-Alias $NAME1 -CsrDetails @{ AlternativeNames = "$SAN1, $SAN2....$SAN10"}. I assume that every SAN must pass for the challenge to validate you own this domain/SAN. So I should register the principal CN and each SAN individually. Am I right?

2.If the above is true, then I read in the rate-limits that we have 100 SAN per domain but 5 attempts to register the same domain per week. I see the limits here:
https://github.com/ebekker/ACMESharp/wiki/Let's-Encrypt-Reference-Sheet
My goal is to register a domain with at least 10 SAN, how can I do this?

Awesome work ebekker!! Keep going with it!

**Comment by WallyRanson** [comment]
1. You should complete the challenge for the principal CN and each SAN individually and then combine them into one certificate with the -AlternativeIdentifierRefs parameter.

2. The limit of 5 is the amount of duplicate certificates, which means a certificate with the same principal CN and SAN. 1 principal CN and 100 SAN is just one certificate in this case.

**Comment by fpeterson194** [comment]
WallyRanson,
Thanks very much for your response. Make sense now.

I´m having issues with the -CsrDetails parameter, I get the following error:

New-ACMEIdentifier : A parameter cannot be found that matches parameter name 'CsrDetails'.
At line:12 char:45
+     New-ACMEIdentifier -Dns $FQDN -Alias $FQDN -CsrDetails @{ Country ...
+                                                ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-ACMEIdentifier], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,ACMESharp.POSH.NewIdentifier

The piece of code I´m executing is the following:

I have a function called: registerFQDN which receives as parameter the CN (or SAN) you want to register.

function registerFQDN{
	$FQDN = $args[0]
	
	echo "`n Creating a new identifier for $FQDN ..."
	New-ACMEIdentifier -Dns $FQDN -Alias $FQDN -CsrDetails @{ Country ="US"; StateOrProvince ="Test"; Locality = "Test"; Organization = "Test"; OrganizationUnit = "Test"; Description = "Testing Phase" } | select status, Expires
	
	echo "`n Completing the challenge for the new identifier for $FQDN ..."
	Complete-ACMEChallenge $FQDN -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebSiteRef = "$iisSiteName" } | select Identifier, status, Expires *>&1 >> $acmeLog
	
	echo "`n Submitting the new identifier for $FQDN ..."
	Submit-ACMEChallenge $FQDN -ChallengeType http-01 | select Identifier, status, Expires *>&1 >> $acmeLog

    do {
        $auth = ((Update-ACMEIdentifier $FQDN -ChallengeType http-01).Challenges | Where-Object {$_.Type -eq "http-01"}).status
        if($auth -eq "invalid") {break}
        echo "`n Waiting for a valid authorization ... Current status is $auth"
	    Start-Sleep -s 3        
    } until ($auth -eq "valid")
    
	Update-ACMEIdentifier $FQDN | select Identifier, status, Expires *>&1 >> $acmeLog
}

Then I call New-ACMECertificate and Submit-ACMECertificate.

If I execute the above function without the -CsrDetails, it works ok. Could you please let me know my mistake here?

Thanks in advance!

**Comment by WallyRanson** [comment]
I have read the info on the site and they all point to New-ACMEIdentifier as the command to use for the parameter CsrDetails, but that does not make any sense, since New-ACMEIdentifier is per hostname and there can be multiple hostnames in a certificate, but only one set of CsrDetails.
It would more sense to have the parameter working with New-ACMECertificate, so try that.

I am unable to test it at the moment, but if I had the option, then I would  fire up PowerShell ISE on a machine and then run the command "Import-Module ACMDSharp".
This should load the module and the auto-completion of commands should kick in, so just type the beginning of the command at the prompt and you should see a list of commands with a fly-over text for parameters.

**Comment by ebekker** [comment]
Where did you find info pointing to CsrDetails as a parameter for `New-ACMEIdentifier`?  That needs to be corrected.

As you suggested, that's a parameter for the `New-ACMECertificate` cmdlet.  You need to make sure all the Identifiers (DNS names) that you want to use are all verified (i.e. Challenge-complete for each one).  Then you can generate a new certificate specifying up to 100 SAN names.  Note the 100 also includes the primary Identifier, so really up to 99 *additional* DNS names on a cert.

**Comment by WallyRanson** [comment]
Your post here: https://github.com/ebekker/ACMESharp/issues/191

**Comment by ebekker** [comment]
Thanks!  I've corrected the comment(s) in that ticket.

**Comment by fpeterson194** [comment]
WallyRanson, thanks for your response! I´m glad you amend that in the other ticket ebekker, excellent :)

I checked that -CsrDetails is a parameter of  New-ACMECertificate as you mention. So I will give a try and come back with my results.

In the meantime I´m stuck in the challenge phase with the Complete-ACMEChallenge. I get Status "invalid" for the certificate. As I read from other issue I created a brand new Alias each time I request an identifier with New-ACMEIdentifier. So I´m ok with that.

I find out that I have a issue with my IIS because when I tried to browse the file created for the challenge with my web browser  (I´m using iis: Complete-ACMEChallenge $FQDNAlias -ChallengeType http-01 -Handler iis -HandlerParameters @{ WebSiteRef = $iisSiteName }) I get HTTP 500.19 error:
<img width="727" alt="http-500-19" src="https://cloud.githubusercontent.com/assets/25730520/22986727/37260de2-f38b-11e6-96aa-26e85abf446e.PNG">

I went to microsoft page with 0x80070021 error message and it seems I have an issue with a locked section in my configuration: "This problem can occur when the specified portion of the IIS configuration file is locked at a higher configuration level". Reference: https://support.microsoft.com/en-us/help/942055/-http-error-500.19-error-when-you-open-an-iis-7.0-webpage

I went to the article describe there: http://learn.iis.net/page.aspx/145/how-to-use-locking-in-iis-70-configuration and tweak my configuration file with the:
<location path="myPathToTheSite" overrideMode="Allow">

However, I´m still stucked there. I cannot get this work. I know this is not an IIS forum, but if you happend to have this issue I would appreciate your help!

Many thanks for your followup on this WallyRanson and ebekker!!

**Comment by fpeterson194** [comment]
I found the solution for the IIS error above. It is here: https://forums.iis.net/p/1219220/2090248.aspx. I post it just if anyone in the future stucks in the same point as me :)
I will continue now with my tests. I will update soon. Thanks!

**Comment by fpeterson194** [comment]
So here is my status:

I passed successfully the challenge. I´m now in the last part. I execute these commands:

New-ACMECertificate $CNAlias -Generate -Alias $sanCertAlias -CsrDetails @{ AlternativeNames = "$SAN1","$SAN2"; Country ="US"; StateOrProvince ="test"; Locality = "test"; Organization = "test"; OrganizationUnit = "test"; Description = "Test" }

No error message for the command above. Then, I executed:

Submit-ACMECertificate $sanCertAlias *>&1 >> $acmeLog

I get the following error:

Submit-ACMECertificate : error:0D06407A:asn1 encoding routines:a2d_ASN1_OBJECT:first num too large
At line:1 char:1
+ Submit-ACMECertificate $sanCertAlias *>&1 >> $acmeLog
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Submit-ACMECertificate], OpenSslException
    + FullyQualifiedErrorId : OpenSSL.Core.OpenSslException,ACMESharp.POSH.SubmitCertificate

I tried to go without CSR by executing:

New-ACMECertificate $CNAlias -Generate -AlternativeIdentifierRefs $SAN1,$SAN2 -Alias $sanCertAlias

New-ACMECertificate : The given key was not present in the dictionary.
At line:1 char:1
+ New-ACMECertificate $CNAlias -Generate -AlternativeIdentifierRefs $SA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ACMECertificate], KeyNotFoundException
    + FullyQualifiedErrorId : System.Collections.Generic.KeyNotFoundException,ACMESharp.POSH.NewCertificate

I tried what bseddon explained here #160. The case for the Aliases are ok, the 3 SANs pass the New-ACMEIdentifier, Complete-ACMEChallenge and Submit-ACMEChallenge sucessfully. I also tried to execute:

New-ACMECertificate $CNAlias -Generate -AlternativeIdentifierRefs @('$SAN1','$SAN2') -Alias $sanCertAlias

but it does not work either.

My main goal is to execute the AlternativeIdentifiers with the CSRDetails parameters. Where is my error?

Thanks in advance for your support!

**Comment by WallyRanson** [comment]
I am not sure where the issue is hidden.
My guess, and its just a wild guess, is an issue with you SAN variable being of the wrong type, like string and not array or something like that.
ebekker can maybe elaborate on that or see what the real issue is. :)

**Comment by fpeterson194** [comment]
Thanks for your response WallyRanson. I agree with you, I will try to make some more testing there. I will wait for ebekker response :)

**Comment by ebekker** [comment]
What values are your `$SAN1` and `$SAN1` variables holding?  In your various attempts you went from passing them *literally* (i.e. passing in the whole string `$SAN1` as the name of an Identifier alias) to passing them in evaluated (i.e. whatever the content of the variable holds), but I don't know if any of those are legal in your case.

An *Identifier Reference* is any one of [3 things](https://github.com/ebekker/ACMESharp/wiki/PowerShell-Module-Design#general):
* A human-friendly alias that you assign
* A system-assigned unique identifier (GUID)
* A zero-based integer index of an Identifier in the Vault

In *almost* all cases, you want to use the alias, and the rules for alias naming don't allow you to specify some of the variations you tried.

What you're pby trying to do is something along these lines:
```PowerShell
PS> New-ACMEIdentifier -Dns foo1.bar.com -Alias foo1
PS> ## Complete validating foo1 (challenge, etc.)
PS> New-ACMEIdentifier -Dns foo2.bar.com -Alias foo2
PS> ## Complete validating foo2 (challenge, etc.)
PS> New-ACMEIdentifier -Dns foo3.bar.com -Alias foo3
PS> ## Complete validating foo3 (challenge, etc.)

PS> New-ACMECertificate -Alias certWithLotsOfFoos -Generate -CsrDetails @{ Country = "US"; <# etc #> } -IdentifierRef foo1 -AlternativeIdentifierRefs ,foo2,foo3
```

In this scenario, foo1 will be your primary Identifer (the CN) and foo1, foo2 and foo3 will be listed as SAN  DNS Identifiers.

**Comment by fpeterson194** [comment]
Ebekker, thanks very much for your details response! Today, while I was waiting for your response, I test the script from @bseddon . He did a great job and has a robust error-catch. However, I´m stucked in the same point even with his script.

I reviewed the your examples above, but still cannot figure out what is the issue. Let me show you my last test:

Again, I validated the main domain and both SANs without problems. Let me show you the error I get in the pic attached

<img width="960" alt="print" src="https://cloud.githubusercontent.com/assets/25730520/23051359/2d85088e-f4a7-11e6-8ef9-5fad0f82715a.png">

These are the values for the vars inside the line New-ACMECertificate:
[DBG]: PS C:\ACMESharp>> $certalias
certdns_2017-02-17--02-54-38
[DBG]: PS C:\ACMESharp>> $mainalias
dns_2017-02-17--02-54-38
[DBG]: PS C:\ACMESharp>> $maindomain
mydomain.com

and the value for $new variable is this one:
<img width="960" alt="photo" src="https://cloud.githubusercontent.com/assets/25730520/23051399/83b0903e-f4a7-11e6-825b-a7c313c064a6.png">

I checked the number of characters of my Alias just in case but they are less than 50 characters as you indicate here: https://github.com/ebekker/ACMESharp/wiki/PowerShell-Module-Design#general

I´m almost there...I really appreciate your effort and time in helping me!!

**Comment by bseddon** [comment]
The script is failing when submitting the certificate.  The error box shows an OpenSSL encoding error.

Searching for 'a2d_asn1_object' I get a number of results.  [This one](http://stackoverflow.com/questions/14679641/ssl-asn1-ecoding-routines-and-x509-certificate-routine-errors) seems to hold some clues.  It suggests that the CSR details may be invalid or that there is an incorrect OID used in the certificate requests (which suggests an invalid OpenSSL configuration).

Now I'm no OpenSSL expert so these thoughts are likely to wrong.  However, I thought I'd add them to help @ebekker as it's unlikely he uses the script.

**Comment by fpeterson194** [comment]
@bseddon thanks very much for your response! I double checked my CsrDetails and they seem to be ok. Based on your script, let me paste the parameters related to the -CSRDetails:

-Country "US" -StateOrProvince "South Lab" -Organization "LAB Test" -OrganizationUnit "Lab Tower" -Description "Test Issuing" -Email "letsencrypt@mydomain.com"

I checked if the amount of characters are ok and they are. Any suggestions?

**Comment by bseddon** [comment]
Unfortunately, I do not have any suggestions except to ask if you have tried to submit a certificate request without including any CSR details?

A question for @ebekker is to learn if the aliases have been created successfully but the submit-acmecertificate command fails is it OK to re-submit?  If there was a previous error because the submission request failed, will ACMESharp keep reusing 'broken' submission details or does each invocation of the submit command start over?

The error message does seem to indicate that there is a problem creating the certificate request. 'asn1' in the error you posted is a reference to 'abstract syntax notation 1' which is used in the generation of certificates and certificate requests.  Clearly something is not correct as fairly low level.

**Comment by fpeterson194** [comment]
@bseddon thanks for your reply. I will test without CSR details to see what happends. I will put my results as soon as possible.

**Comment by fpeterson194** [comment]
@bseddon here the output of my test:
 
I passed no CSR details as parameters

I didn´t have the issue below but now I get this error:

Creating a new certificate for domain 'myDomain' with alias 'certdns_2017-02-17--19-54-46'
  With these alternative names:
  oneSan1,oneSan2 (Comment: I modified this values on purpose)
The current ACME certificate has id '70406aea-2b36-4ecb-b057-2ad3fd5bd6ed' and thumbprint '4D653B235E4A6703311C361E62B9548D6F194EA4'
Get-ChildItem : Cannot find path 'C:\Certificates\certdns_2017-02-17--19-54-46.pfx' because it does not exist.
At line:598 char:36
+     if ( ! $noCertOverwrite -or ! (Get-ChildItem -Path $filepath) )
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Certificates...7--19-54-46.pfx:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Certificate exported with thumbprint '4D653B235E4A6703311C361E62B9548D6F194EA4'
Importing to \LocalMachine\WebHosting from C:\Certificates\certdns_2017-02-17--19-54-46.pfx
Setting friendly name to 'myFriendlyName 2017-05-18 LE'
No IIS

I got the certificate created but with no SAN. I checked the Subject field and they were not there.

So I have for sure one issue with my CSR details. But I don´t have neither any special character nor long strings of characters to hit some limit.

On the other hand, Do you know about the issue above? Seems not to find the path but the file it is there as the script can import later the certificate to the local store (task done successfully).

I´m almost there...I really appreciate your time and effort in helping me with this!!

**Comment by WallyRanson** [comment]
try to leave your email out the entries in the CsrDetails.
If that does not work, then try to only use one entry at a time to figure out if one of them does it.

The reason why I am asking to leave out email first is because I have previously seen scripts that have problems with special characters in double quoted strings.

**Comment by bseddon** [comment]
@fpeterson194 Take a look at [this comment](https://github.com/ebekker/ACMESharp/issues/98#issuecomment-185993271).  Back in the day when I was new to ACMESharp I also ran into the problem you describe trying to export the certificate using the PFX format.  The reason I experienced the problem is that the LE intermediate certificate was not in my Windows certificate store. Because it was missing the PFX could not be generated.  Maybe this is also your issue?

**Comment by fpeterson194** [comment]
About the CSRDetails error:

@WallyRanson thanks very much for the troubleshooting advice. I find out which is the parameter that cause trouble. I tested one by one and the "description" parameter is the one that brings this openssl error message :)

@bseddon : Do you experience any issues with the -Description parameter? Does it work for you? I make several tests and even putting only the description parameter in the -CSRDetails brings the error message above explained. I tried with each individual parameters and even all of them but Description and the error is not present anymore. Any ideas?

@WallyRanson @ebekker @bseddon : Even executing successfully the certificate creation (without description field in the CSRDetails parameter) the details are not present in the Subject field within the certificate. Did you test this option? It works for you? I don´t get any error message. The fields are just not there. Thanks very much for all of you for you patience and time to help!! I´m very glad to work with you and to use the solution.

About the path error:

I noticed that the Root CA of the Staging environment was not added to my trusted store. I added it. I ran the script again, but I´m still getting the same error:

The current ACME certificate has id 'feeb5a5d-0c82-4274-8c6e-f6ba0b914615' and thumbprint '9913B694CCB14CA851A140003CCFD01D9C5AACCD'
Get-ChildItem : Cannot find path 'C:\Certificates\certdns_2017-02-20.pfx' because it does not exist.
At line:526 char:36
+     if ( ! $noCertOverwrite -or ! (Get-ChildItem -Path $filepath) )
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Certificates\certdns_2017-02-20.pfx:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

The line which produces the "error" is this one:

if ( ! $noCertOverwrite -or ! (Get-ChildItem -Path $filepath) )

In my test, $noCertOverwrite was TRUE and $filepath is C:\Certificates\certdns_2017-02-20.pfx

If I checked the folder Certificates I confirm that at that point of the execution, there is no certificate in the folder with the name specified, so seems that the error message is consistent. My guess is that this is not an error, do you agree? If so, how can we avoid it?

Let me know your thoughts.

Thanks in advance!

**Comment by bseddon** [comment]
@fpeterson194 You asked: It works for you?

Yes, checkout the certificate on one of my sites: www.wproute.com.  You will see it is a Let's Encrypt certificate created on Feb 12th. It includes several other sites in the Alternative Subject Names field.  This certificate was generated using the script and ACMESharp.

Let me know if seeing the command I used to run the script might help.

I cannot say why the .pfx file cannot be found.  Where does the 'C:\Certificates\' path come from?  The path used by the script is passed in using the variable $certFolder which has a default value of $env:temp. On my machine $env:temp resolves to the path 'C:\Users\<user>\AppData\Local\Temp\2'

Are you passing a specific certificate location path?

**Comment by fpeterson194** [comment]
@bseddon Thanks for you quick reply! I checked your site. I can get the SANs perfectly. My issue is with the details like Organization, OrganizationUnit, Email, Description, etc. If I check your certificate you have no details about these parameters on it. In the subject field you have: CN = www.wproute.com.

About the path, yes. I pass my own path to the script with the parameter: -certFolder "C:\Certificates"

**Comment by bseddon** [comment]
@fpeterson194  As far as I know, the subject field of any certificate generated by Let's Encrypt can only show the 'main' domain associated with the certificate.  As you see, in the case of the www.wproute.com site this domain is the main domain.  The same certificate is able to support all the related sites because they exist in the ASN field.

I agree that the CSR values are not being added to a certificate.  My command adds the organization and email values but these values do not appear in the certificate.

@ebekker This facility used to work.  Maybe the change to have ACMESharp use OpenSSL has meant the CSR parameters are no longer included?  Of course it could be an issue on the LE servers.

The PFX export works for me.  The line:

if ( ! $noCertOverwrite -or ! (Get-ChildItem -Path $filepath) )

means if you allow certificate overwrite or there is no existing file then export a new copy of the PFX.  Else use the existing one.  I apologise for the double negative ( ! $noCertOverwrite ).  When I first started writing PS scripts I did not know how to set a default value of '$True' for a boolean parameter.  So the workaround was to use a $False default on a negative parameter name.

If you change the second condition in the 'if' test from 

 ! (Get-ChildItem -Path $filepath)

to

 ! (Test-Path $filepath)

Does it work for you?

**Comment by fpeterson194** [comment]
@bseddon Thanks for your response again. Yes, that is the point. Let´s wait for @ebekker response on the CSRDetails point.

Regarding the PFX export, I changed the condition with ! (Test-Path $filepath) and I get no more the previous error message. Wonderful :)

In my humble research and testing, I found out several little things to improve in your script. Once I solve all my issues here, if you are interested @bseddon I will give you my updated version of your script with a list of things I included on it. I want to make a contribution for all the help here :)

I tested the IIS auto-configuration and it works good. I can access my site directly through HTTPS with the brand new LE certificate. However, I was wondering what the following lines do:

```
# Remove the existing binding.  The binding must be here, a check was made at the beginning
        "Removing the SSL certificate for '$domain'"
        remove-item -path "IIS:\SslBindings\*!443!$domain"
        "Adding the SSL certificate with thumb print '$thumbprint' for '$domain'"
        $result = New-Item -Path "IIS:\SslBindings\*!443!$domain" -Value $import_result -SSLFlags 1
```
I know they do the binding, but when I use the dubugger line by line I see no changes in the IIS UI for the bindings (removing/adding). In fact, if I check my site (the bindings section) I still see the old self-signed certificate I created assign to it. However, if you access the web site, you see the LE certificate. Is this some kind of issue with updating the UI here?

Other warining I´m getting from IIS is this:
WARNING: Binding host name 'oneOfMySANsDomain' is not equals to certificate subject name 'mainDomain'. Client may not be able to connect to the site using HTTPS protocol.

However, I can connect successfully to the main domain and even both SANs. Any thoughts on this?

Thanks!

**Comment by bseddon** [comment]
It would be great if you can consider post a pull request to @whereisaaron https://github.com/whereisaaron/acmesharp-update-certificate.  Aaron has updated the script in a number of way most notably to add support for the DNS challenge method.  I have not used Aaron's update because the script I have works for me but his is the most advanced version of the script.

When a certificate is updated is must be removed from IIS and added back or IIS will continue to use the original certificate even if it has been updated in the certificate store.  Presumably this is some kind of fail-safe behaviour. Manually this is accomplished using the IIS manager to remove and re-select the certificate from the store.

As you write, the lines you quote perform the same actions in script using the IIS schema implementation for PowerShell complete with all the weird syntax.

My guess is that the IIS UI does not update its references until it is closed and re-opened because either the update to the SSL bindings does not fire an event or the UI does not listen for such events.

I also see the warning.  This warning seemed to appear after I updated to ACMESharp 0.8.1.  I have not investigated the reason for these messages because, as you mention, it does affect updating the certificate.  It's hard to understand why an update to ACMESharp will result in this message so maybe there was KB update to IIS or PowerShell recently.

**Comment by fpeterson194** [comment]
@bseddon thanks for the @whereisaaron repo link. I appreciate it.

It is strange, I closed the IIS windows, open it again and the same old certificate is assigned to the site. However, as I mentioned, it works successfully. Some kind of refresh issue. Let´s leave it for now.

Ok, good to know you have the same warning as me. Ok, no problem. Thanks for the confirmation.

One thing I´m concern is the way you update the bindings, because you put a *. My question is if I have several sites under the same IIS server, will it change all the bindings for all of them? I found out other syntax in some powershell forums that allows you to specify the specific site by parameter. I didn´t test it yet, just FYI :)

@ebekker Could you please let me know if the CSRDetails is nowadays working or we have a bug here? @bseddon and me are experience the same behaviour. I would appreciate your response on this! Thanks!!

**Comment by bseddon** [comment]
I don't think you need to be concerned by the syntax and the use of wildcards.  I also run several sites under IIS and it works OK.  This is because the SSL bindings are *domain* specific.  So there is a pair of relationships:

`IIS site -> domain -> SSL binding`

You can see the domain is part of the binding:

`"IIS:\SslBindings\*!443!$domain"`

A domain can be assigned to only one site on a single IIS instance so updating the domain's SSL binding  has the effect of updating IIS (or it does in my case).

**Comment by fpeterson194** [comment]
Excellent @bseddon ! Make sense. I agree. Thanks very much again for all your responses and comments!!

Last thing would be to wait @ebekker to see if we have an issue or not with the -CSRDetails parameter.

**Comment by fpeterson194** [comment]
@bseddon quick one: Do you know when the binding is performed if an iisreset is done behind the scenes? I tested certbot in linux with apache and you need to make a web server re-start.

**Comment by bseddon** [comment]
I do not know the order used by iisreset.  It it should not be necessary to reset IIS because the SSL bindings are effective immediately.  The Windows file system is based on a protocol called SMB.  SMB implementations (including Samba on Linux) generate events when files are added, deleted and updated.  Windows application software can subscribe to and listen for these events and so are able to update their state automatically.  For example, Windows Explorer listens for these events so it can update the displayed folders and files.  

The IIS service (w3svc) listens for these events to update its SSL bindings without the need for a restart.  The binding information is held in a config file so when the bindings are changed a file is updated, an event is fired and listening applications like w3svc can update their state.

Apache could listen for equivalent events on Linux but it does not.  As a result its necessary to restart the Apache service manually or automatically using a script.  In my experience the same is true for other Linux base web server such as nginx.

**Comment by fpeterson194** [comment]
@bseddon thanks very much for the explanation! Good to know :D

**Comment by fpeterson194** [comment]
@ebekker do you have an update about the -CSRDetails parameter? Thanks in advance!!

**Comment by ebekker** [comment]
So I ran through a few iterations of this myself.  I verified that the CSR details such as Org, OrgUnit, Country, Province, Locality *are* getting captured and included in the generated CSR file.

You can verify this yourself for your own certificate submissions using OpenSSL.  You can use the "OpenSSL.Light" port of OpenSSL for windows -- easiest way is to use chocolatey to install it (e.g. `choco install OpenSSL.Light`).  Once OpenSSL is installed, in your Vault, under the directory `55-CSRPM` are all the generated CSR files just as they are submitted to Let's Encrypt.

To verify the decoded content of the CSR file, you can issue the following command in CMD:
```
"C:\Program Files\OpenSSL\bin\openssl.exe" req -text -in PATH-TO-CSR.PEM
```

So, having said all that, I can tell you that all the test CSR I have do include all the elements I specified in `-CsrDetails` and that CSR file in the Vault is literally what gets submitted to LE for generating a certificate.  So somehow it's being dropped or ignored by LE.

**Comment by ebekker** [comment]
Actually, it looks like this is now by design and completely intentional:  https://community.letsencrypt.org/t/all-distinguished-name-fields-now-showing-in-issued-certificates/15397

I do recall that LE used to honor most of the elements in the Subject of a submitted CSR, but that was early on (and perhaps only against the STAGING server), so it looks like their official stance now is that they don't including any of those fields in the certificate because they cannot verify them and therefore cannot certify against them.

**Comment by bseddon** [comment]
@ebekker Good find.  The LE forum provides a good explanation of why we n o longer see the extra field values.

**Comment by ebekker** [comment]
Related issues from certbot:  https://github.com/certbot/certbot/issues/2317

**Comment by fpeterson194** [comment]
@ebekker excellent! I read all your comments and the LE article. It make sense not to have these details as LE can only provide DV and not OV.
So, the only thing left to tell here is THANK YOU ALL!! @WallyRanson @bseddon and @ebekker. I really appreciate all your help here!! :) Closing the issue.

**Comment by ebekker** [comment]
You should close if you're satisfied with the result.

**Comment by fpeterson194** [comment]
@ebekker more than satisfy with your support! :) Closing the issue.
