### ISSUE TITLE
ACMESharp Get-ACMECertificate : asset file does not exist

### ISSUE THREAD

**Issue by mbroz87** [ebekker/ACMESharp#238]
Dear Support.

I really don't know, how to solve error below.

I tried to google it, even on github.

 Waiting for a valid authorization ... Current status is valid
Get-ACMECertificate : asset file does not exist
At C:\xxxxxx\ACME-Exchange\ACME-Exchange.ps1:79 char:1
+ Get-ACMECertificate $SANcert_alias -ExportPkcs12 $SAN_pfxfile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ACMECertificate], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,ACMESharp.POSH.GetCertificate

Do I have to install root certificates?
https://letsencrypt.org/certificates/

I can provide PS code as well, but I download from some site and it names ACME-Exchange.ps1

Thank you.

Mark.

**Comment by animetauren** [comment]
Not really support, i found the script you mentioned, can you verify that you uncomented line 66?

**Comment by mbroz87** [comment]
Hello animetauren.
Yes, it is uncomented.
Mark.

**Comment by gbeekmans** [comment]
Hi Mark,

I ran into the same issue today while I was experimenting with a new script. Check the following, your issue might be related.

Check the contents of your Vault's directory, ie: `C:\ProgramData\ACMESharp\sysVault`

In my case the error happened due to missing `75-ISUPM` and `76-ISUDR` directories.

After successfully obtaining a certificate you should have the following directories (at least based on my own experience):

```
30-CSRDT
40-KEYGN
45-KEYPM
50-CSRGN
55-CSRPM
65-CRTPM
66-CRTDR
75-ISUPM
76-ISUDR
```
In my own case, the problem was triggered by removing the contents of this directory but leaving the `.acme.vault` and `00-VAULT` files around. Upon the next run, the `Update-ACMECertificate` cmdlet would create all the directories above with the various files, but `75-ISUPM` and `76-ISUDR` would not re-generate. I haven't figured out yet the particulars of it.

I think your ACME-Exchange script does a clean-up at the end and removes the contents of sysVault and leaves a few files behind (`.acme.vault` and `00-VAULT`).

Alternatively, you could delete everything including those two files and essentially start from scratch each time you run it (ie: every 60 days).

I'm not sure what the recommended best practices here are, but hopefully the above info helps point you in the right direction.

Gerard.

**Comment by jarmediagmbh** [comment]
I had the same issue ("asset file not found"). The comment of gbeekmans pointed me in the correct direction. 
My script now begins with a
`Remove-Item "C:\ProgramData\ACMESharp\sysVault\*" | Where { ! $_.PSIsContainer }`
So it will basically delete the whole sysVault-Directory. With this workaround applied, my problem was solved.

**Comment by ebekker** [comment]
I'm afraid I can't help with the `ACME-Exchange.ps1` script as that was contributed by another party and I don't have access to the environment to help troubleshoot this.  Please contact the original author for assistance.
