### ISSUE TITLE
Authorize Failed 

### ISSUE THREAD

**Issue by warrenkc** [ebekker/ACMESharp#263]
Hi. I have been using win simple to get certificates for a while. However 95% of the time now, I get the error saying: Auhorization Result: invalid. What can I do to diagnose where the issue is?
I test to see if the file is accessible, it loads fine from any browser:
[http://eshgalleryauction.com/.well-known/acme-challenge/7x_ZRRebBCcdhrVqm1WGFgX3aCHf0-0t9xYekEdcEWY](http://eshgalleryauction.com/.well-known/acme-challenge/7x_ZRRebBCcdhrVqm1WGFgX3aCHf0-0t9xYekEdcEWY) 

![image](https://user-images.githubusercontent.com/6418791/28416996-f542bb5a-6d88-11e7-8ccc-b852ab4b426c.png)

Thank you for your help and time,
Warren

**Comment by cpu** [comment]
Hi @warrenkc,

I'm not a developer or a user of ACMESharp, but I saw your problem and was curious so I checked the server-side logs from the Let's Encrypt validation authority to see what the problem could be.

I believe the root problem is that your authoritative nameservers for `eshgalleryauction.com`: `ns1.gear.host` and `ns2.gear.host` seem to either timeout or return `SERVFAIL` for CAA lookups. I'm able to replicate this reliably from my own computer with `dig`:

```
$ dig @ns1.gear.host type257 eshgalleryauction.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @ns1.gear.host type257 eshgalleryauction.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

$ dig @ns2.gear.host type257 eshgalleryauction.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @ns2.gear.host type257 eshgalleryauction.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

```

The reason this used to work but has broken [is explained in an API announcement post on the community forum](https://community.letsencrypt.org/t/caa-servfail-changes/38298). You will need to contact the folks running your authoritative nameservers and have them investigate the cause of this. It's likely that there is a firewall or some configuration option that is blocking CAA type queries. Soon *all* CA's will be forced to ask your nameservers for these record types so it's definitely something to get fixed ASAP! You could also switch to a different nameserver provider.

Since this isn't a ACMESharp issue I recommend that if you need more help you post on the [community forum](https://community.letsencrypt.org). There are a number of other people in the same boat and we're actively helping them there as we can.

For the developers of ACMESharp: It seems like the output above is masking the Problem detail returned from validation:

```
"Error":"urn:acme:error:connection :: DNS problem: query timed out looking up CAA for www.eshgalleryauction.com"
```

It would probably help users if this detailed message was bubbled up in the interface.

Hope this helps!

**Comment by warrenkc** [comment]
Your reply is very helpful. Thank you.

**Comment by warrenkc** [comment]
Hi. Where can you see the server-side logs from the Let's Encrypt validation authority? That would be helpful.

**Comment by cpu** [comment]
Hi @warrenkc, they aren't available to the public.

I'm a developer for the server-side of Let's Encrypt, [Boulder](https://github.com/letsencrypt/boulder), and have privileged employee-only access that lets me view logs.

**Comment by warrenkc** [comment]
Okay. Thank you. I am on windows 10. Do you know a way to test the CAA Record for a domain? I asked my hosting company to add the DNS record, but I am still getting the same error as before (as far as I can see).

I was reading about CAA from :  [this site.](https://ma.ttias.be/caa-checking-becomes-mandatory-ssltls-certificates/)
It says:
**Do I have to add CAA records to get a certificate?**
No, just like HSTS, the CAA records are completely optional. You should add them, for increased security though.

As of September 2017, Certificate Authorities are obligated to check for CAA records and honor those preferences. Not having CAA records is essentially the same as saying "everyone can issue a certificate for my domain".
---------------------
But it seems that Let's Encrypt does require them. 
Thank you for your help.

**Comment by jsha** [comment]
@warrenkc it's worth noting, though, that even without access to Boulder's server-side logs, most ACME clients provide much more detailed log output than the ACMESharp output you posted. In particular, "urn:acme:error:connection :: DNS problem: query timed out looking up CAA for www.eshgalleryauction.com" is a user-facing error message and ACMESharp should have shown it to you.
