### ISSUE TITLE
Local WebServerProvider to complete the challange (Needed e.g. for a FritzBox)

### ISSUE THREAD

**Issue by Peter8Dev** [ebekker/ACMESharp#42]
Hi there,

I really like the Idea and the usage of this Project. I think I could already do what I need with the current implementation but I want to have it more easy and maybe also usable for a lot of other people. 

My use case is the following. I have a Fritzbox (Router) that supports accessing via HTTPS and also uploading a userdefined certificate, but I have no access to the root folder, so I cannot place the file to ".well-known....". My solution is to make a port forwarding and create a local temporary webserver on my Windows machine to complete the ACME challange there and then upload the certificat on the router. 

I know that there are plenty of other solutions (Linux VM, jailbreak the router, and so on) but for me it seems to be the easiest solution.

As far as I understand the code, I simply write a WebServerProvider that then hosts the file locally, where a simple http server can be used. In detailed it might be more tricky, but I think it should work in this way.

Is anybody interrested in this enhancement or is this to far away from the idea of this project?
Or can maybe someone just implement this in a short time, because I have to get more into the code to write something that might be usable for others. 

Thanks in advance for any notes, suggestions or help.

**Comment by ebekker** [comment]
One alternative is to use the DNS Challenge Type instead of the HTTP Challenge Type, then all you have to do is manipulate some DNS records to prove ownership and control of a domain name.

There are two DNS Challenge Handlers that exist today, `manual` and `awsRoute53`.  If you host your DNS in AWS, you can use the latter and it will take care of everything for you.  Otherwise you can use the former and just follow the instructions it spits out.

See the [release announcement](https://groups.google.com/d/topic/acmesharp/sPYPFwPVQ5Y/discussion) for more details.

I'm going to close this issue for now.  If you decide you want to pursue a custom HTTP Challenge Handler for your special case, you can either reopen to continue the discussion or simply fork and implement your Handler in your local clone.
