### ISSUE TITLE
AWS PowerShell conflict

### ISSUE THREAD

**Issue by bseddon** [ebekker/ACMESharp#83]
When I build ACMESharp the resulting POSH folder contains all the AWS DLLs.  At the moment I'm copy these files into an ACMESharp folder on my web server.  However, this causes a problem whenever I try to use Route53 AWS PowerShell cmdlets after the ACMESharp module is loaded.

The problem is that AWS command are conflicted about the assembly DLLs loaded.

Is it necessary to copy the AWS assemblies from the POSH build folder?  I imagine they appear in the folder because they are referenced by an ACMESharp project and MSBuild copies them by default.

**Comment by ebekker** [comment]
Hmm, that's an interesting conflict, I haven't run into that myself, and I'm in a similar situation (have ACMESharp module loaded and also using AWS cmdlets).

If you unload the ACMESharp module (e.g. `Remove-Module ACMESharp`, does that restore the AWS cmdlets to working status?

Also, what type of error are you seeing?  Are the AWS cmdlets throwing exceptions?

**Comment by ebekker** [comment]
Also, do you encounter a conflict in the other direction -- that is, if you load the AWS module and use some of those cmdlets, then try to load and use ACMESharp, do you get an error there too?

**Comment by bseddon** [comment]
"have ACMESharp module loaded and also using AWS cmdlets"

Do you have the AWS assembly DLLs in the same folder as ACMESharp.DLL?  If I delete the AWS assemblies copied by MSBuild out of the build folder it works just fine.  I guess I'm just checking this is an OK thing to do.

I'm using the AWS Powershell shortcut so by the time ACMESharp is loaded, PowerShell has loaded the AWS commands and at least some of the AWS assemblies that are already available in the global cache.

"If you unload the ACMESharp module..."

I don't think that can work,  When a .NET AppDomain is loaded into a process such as PowerShell (I'm using the ISE) it cannot be unloaded.  PowerShell may make the Assemblies unavailable but until the process that created the AppDomain is terminated, the assemblies are there for good.

"Are the AWS cmdlets throwing exceptions"

Yes.  I created a PowerShell function to add a TXT record.  It begins:

$CreateRecord = New-Object Amazon.Route53.Model.Change

And then uses this instance as a parameter to the command Edit-R53ResourceRecordSet.  

The error is that the type 'Amazon.Route53.Model.Change' does not match the type 'Amazon.Route53.Model.Change' which of course look nonsense but could be true if the Amazon.Route53.Model.Change instance is created from the definition in the AWS assembly in the ACMESharp folder but the Edit-R53ResourceRecordSet command is derived from an assembly of the AWS set in the global cache.

"do you encounter a conflict in the other direction?"

I've not tried because I'm using the AWS PowerShell shortcut. My guess is that the problem would not arise because the AWS assemblies in the ACMESharp folder will be used in preference to the ones from global cache.

**Comment by ebekker** [comment]
So perhaps the reason I have not seen this is that I don't use the AWS link to shell.  What version of PS are you using?  In version 4+ you don't really need to use the shortcut because PS will automatically load modules as necessary upon first reference.

Is there any reason you *need* to run the AWS pre-loaded session?

**Comment by ebekker** [comment]
So a couple changes that will potentially improve the situation is that currently the main ACMESharp module has a dependency on AWS SDK libs, which is legacy and will be removed soon.  Once that';s done the core module will no longer have the SDK libs shipped with it.

**However**, the add-on providers for S3 and R53 obviously will have the dependency and they will need the SDK libs.  If you use the choco or PS Gallery installation, they will install the "full" distribution with the AWS SDK libs.  And this is pby a better solution for *most* folks as they won't always have the AWS SDK/CLI/PS extensions installed on their system.

I'm not really sure how to help your situation since there isn't a way to really selectively copy/install those DLLs.  I would recommend using ACMESharp in a *clean* PS shell.

**Comment by bseddon** [comment]
You've answered my core question by letting me know its OK to jettison the AWS SDK DLLs and use the ones from full SDK (if we need them). Thanks.
