### ISSUE TITLE
Delete/Remove ACMEIdentifier

### ISSUE THREAD

**Issue by Xyanid** [ebekker/ACMESharp#88]
I tried to complete and submit a challenge and failed because of some miss configuration. Unfortunatly its impossible to delete an ACMEIdentifier, so I have to create the same ACMEIdentifier using a different Alias I assume. 

I would rather delete the old ACMEIdentifier and recreate it, cause if this is the way things are done, then after a while the Vault might get clustered with invalid ACMEIdentifier that can never be removed.

So unless I am missing something, I would suggest to implement the ability to remove ACMEIdentifiers.

**Comment by bseddon** [comment]
I don't think it makes sense to delete an identifier.  An identifier is an ACMESharp concept that associates an alias with a collection of information on the LE servers.  The information on the LE servers can be accessed using the value of the Uri property of the ACMESharp identifier.  Since you cannot delete the information on the LE server, even if it is redundant, does it make sense to get rid of the identifier?

If you really want to remove the identifier you can remove it from the ACMEVault file.  This is a text file in a JSON format.  The identifiers are easily found.  However, you will need to review the file for any objects that rely on the identifier as any resources created by them will need to be removed.  These resources, such a downloaded tokens and certificates, can be found in various of the sub-folders of the vault folder.  The resources are identified by UUIDs.

**Comment by Xyanid** [comment]
The question is then, how can you resubmit a failed ACMEChallenge? It would remain in the vault forever and you can not finish it according to [this](https://github.com/ebekker/ACMESharp/wiki/Quick-Start#6b-check-the-status-of-the-challenge) right? 

Recreating the ACMEIdentifier is also impossible because it would essentually be the same as an already existing one, but you would have to use a different/new Alias. 

Simply resubmitting a challenge would be the best solution I guess. You simply failed the challenge since the LE Server did not get the information he wanted, so a reattempt to resolve it does not seem that unreasonable to me, unless it is impossible based on the way the LE server handles challenges ofc.

But as it is manually possible to delete an identifier; I guess it can be used as workarround at this point.

**Comment by bseddon** [comment]
Yes the attempts will accumulate in the vault.  The failed attempts also remain on the LE servers.  Since the identifier references these files (which will record the failed validation status) the identifier can't be reused.

If you have an absolute need to retain the alias (which is just a made up name) you will need to remove the entries from the vault files.  But you could just use a new alias. The vault doesn't consume much space.  I've generated about 40 certificates (mainly testing) and the whole vault which includes the various certificates is less than 1MB (and nearly half of that is backup).

Alternatively you could delete the vault and create a new one.

**Comment by ebekker** [comment]
Thanks @bseddon, yes, that is correct.  The ACME protocol (that powers the Let's Encrypt service) doesn't allow you remove existing Identifers or failed Challenge attempts.  Instead, it just steers you to create a new Identifier, which you can do with the same DNS name as a previous Identifier entry.

So, you just create a new Identifier with the same DNS name (but a new unique Alias) and then attempt to complete the Challenge(s) on it.

**Comment by ebekker** [comment]
I believe the original question has been addressed, so I'm going to close this out.  If not, please reopen and continue the discussion.

**Comment by mikeobrien** [comment]
So is the alias an ACMESharp concept or a ACME concept? If the former, would it make sense to allow the user to reuse the alias? I'm totally new to this so might be missing something, but when I come back to this next year to renew (or whatever) I'll have to remember which aliasN is the one I need to use (e.g. "wait, was it 'myalias2' or 'myalias3', can't remember..."). I'm assuming you could enumerate them and figure it out but seems like it would be more convenient to have your alias point to the *valid* one if there were multiple failed ones. That way I know that the valid one is always 'myalias'.

**Comment by bseddon** [comment]
An alias is an ACMESharp concept that is a proxy for some data retained on the LE servers for 294 days (why 294 - who knows) that indicates the validation status of a single domain.

In turn, an alias (and the data on the LE servers for which it is a proxy) is associated with one and only one certificate (a certificate may reference the validated domains associated with one or more aliases).  Certificates will expire in 90 days (an LE hard limit).

The bottom line is that you cannot reuse an alias because you cannot reuse the data on the LE servers for which it is a proxy. In 90 days time you will need to use a new alias.

There are an infinite number of aliases so you can create a new alias next time, perhaps with a sequence number.  I use the date.  

You can query existing aliases to determine the previously used alias(es).  The example in #112 shows how to query the most recent alias used to create a certificate for a specified domain.

**Comment by ebekker** [comment]
@mikeobrien, I think your point is valid, so I've created issue #118 to track the more generalized request to allow aliases to be reassigned or unassigned.

**Comment by mikeobrien** [comment]
@ebekker thx!

**Comment by ebekker** [comment]
As described in #118, you now have the ability to rename or remove an alias associated with an Identifier or a Certificate, so you can *move* a target alias around as needed.
